### ISSUE TITLE
Allow speeds greater than 1Gb/s to be displayed

### ISSUE THREAD

**Issue by ulope** [bchretien/tcptrack#2]
Currently tcptrack shows "LUDICROUS" in the throughput column for speeds greater than 1Gb/s. While funny this makes it very much useless in 10Gb networks.

Also there is a comment in the source that says "not enough room to display it" which is nonsensical since 1Gb/s already is displayed as a three digit MB/s figure.

**Comment by bchretien** [comment]
Oh, I completely missed that issue, sorry! I guess that part of the code is quite old, and the creator did not plan that far ahead.

**Comment by bchretien** [comment]
Please let me know if that works for you (if you still need this :wink:).

**Comment by jeteon** [comment]
Aw...I was rather fond that little thing. It added sunshine to my day when dealing with issues around saturated 1Gps links. It would be cool to have it as a fraction of the link speed.
